# remote_theme: "jekyll/minima"
theme: minima
title: Photos of Swampscott, MA
description: Photographs of landmarks and historic places in Swampscott, MA
show_downloads: false
show_excerpts: false
markdown: kramdown
